export const DEFAULT_VIDEO_ENHANCEMENT_SETTINGS = {
  enabled: false,
  enableCoverImage: true,
  enableTranslation: true,
  showLoadingIndicator: true,
  enableReviewBreaker: true,
  enableFC2Breaker: true,
  enableWantSync: true,
  autoMarkWatchedAfter115: true,
  autoMarkWatchedStars: 4,
  enableActorRemarks: false,
  actorRemarksMode: 'panel' as const,
  actorRemarksTTLDays: 0,
  actorRemarksTaskTimeoutSeconds: 10,
  enableVideoFavoriteRating: true,
  enableRelatedLists: true,
  enableExternalEntryPanel: true,
  enableExternalSearch: true,
  enableOnlineAvailability: true,
  showOnlineAvailabilityFailures: false,
  onlineAvailabilitySites: {} as Record<string, boolean>,
  enableSubtitleSearch: true,
};